name: Packer Create Image for Node.js App

on:
  pull_request:
    branches:
      - main
  # push:
  #   branches:
  #     - main  # Trigger workflow on push to the main branch
  # pull_request:
  #   types:
  #     - closed  # Trigger workflow only when a pull request is closed

jobs:
  packer-buildimage:
    runs-on: ubuntu-latest
    #if: github.event.pull_request.merged == true || github.event_name == 'push' 

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Start MySQL Service (for integration tests)
      - name: Configure MySQL Database
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql

      # Wait for MySQL to be fully up and running
      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to start..."
          sleep 10
          sudo mysql -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS \`${{ secrets.DB_NAME }}\`;"

      # Configure environment variables required for the application
      - name: Configure Environment Variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env  
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          ls -al
          cat .env
          cp .env packer/

      # Install application dependencies
      - name: Install Dependencies
        run: npm install

      # Run integration tests (workflow fails if tests fail)
      - name: Run Integration Tests
        run: npm test  

      - name: Zip Web App
        run: |
          mkdir webapp                     
          cp -r $(ls -A | grep -v '^webapp$') webapp/                
          zip -r webapp.zip webapp -x "webapp/node_modules/*" "webapp/.git/*" 
          mv webapp.zip packer/            
          ls -al 

      # Set up AWS CLI for authentication
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Authenticate with Google Cloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

       # Install Packer using the official GitHub Action
      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Initialize Packer
        run: |
          cd packer
          packer init .  

      # Building a custom image for AWS & GCP in parallel using Packer
      - name: Build Custom Image with Packer
        id: packer
        run: |
          cd packer
          packer build .

          AMI_ID=$(aws ec2 describe-images --owners ${{ secrets.AWS_DEV_ACCOUNT_ID }} --query 'Images | sort_by(@, &CreationDate) | [-1].ImageId' --output text)

          if [ -n "$AMI_ID" ]; then
            echo "New AMI created: $AMI_ID"
            echo "AMI_CREATED=true" >> $GITHUB_OUTPUT
            echo "AMI_ID=$AMI_ID" >> $GITHUB_OUTPUT
          else
            echo "No new AMI was created"
            echo "AMI_CREATED=false" >> $GITHUB_OUTPUT
          fi

      - name: Share AMI with Demo Account
        if: steps.packer.outputs.AMI_CREATED == 'true'
        run: |
          aws ec2 modify-image-attribute --image-id ${{ steps.packer.outputs.AMI_ID }} --launch-permission '{"Add":[{"UserId":"${{ secrets.AWS_DEMO_ACCOUNT_ID }}"}]}'

