name: Packer Create Image for Node.js App

on:
  pull_request:
    branches:
      - main
  # push:
  #   branches:
  #     - main  # Trigger workflow on push to the main branch
  # pull_request:
  #   types:
  #     - closed  # Trigger workflow only when a pull request is closed

jobs:
  packer-buildimage:
    runs-on: ubuntu-latest
    #if: github.event.pull_request.merged == true || github.event_name == 'push' 

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Start MySQL Service (for integration tests)
      - name: Configure MySQL Database
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql

      # Wait for MySQL to be fully up and running
      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to start..."
          sleep 10
          sudo mysql -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "CREATE DATABASE IF NOT EXISTS \`${{ secrets.DB_NAME }}\`;"

      # Configure environment variables required for the application
      - name: Configure Environment Variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env  
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env

      # Install application dependencies
      - name: Install Dependencies
        run: npm install

      # Run integration tests (workflow fails if tests fail)
      - name: Run Integration Tests
        run: npm test  

      # #  Building the application artifact
      # - name: Build Application Artifact
      #   run: |
      #     mkdir -p build
      #     zip -r build/webapp.zip . -x "node_modules/*" ".git/*"

      # # Moving the artifact to the Packer directory
      # - name: Move Web App to Packer Directory
      #   run: |
      #     mv build/webapp.zip packer/

      - name: Zip Web App
        run: |
          zip -r webapp.zip packer
          mv webapp.zip packer/


      # Set up AWS CLI for authentication
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Authenticate with Google Cloud
      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Create .env file
        run: |
          echo "MYSQL_DB_USERNAME=${{ secrets.DB_USER }}" >> .env
          echo "MYSQL_DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "MYSQL_DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "MYSQL_DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "MYSQL_DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          cat .env
          mv .env packer


       # Install Packer using the official GitHub Action
      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      # Building a custom image for AWS & GCP in parallel using Packer
      - name: Build Custom Image with Packer
        run: |
          cd packer
          packer init .
          packer build .
         

